Web_CRUD_Contatos/Models/Contato.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Web_CRUD_Contatos.Models
{
    [Table("Contato")]
    public class Contato
    {
        [Column("id")]
        [Display(Name = "Código")]
        public int id { get; set; }

        [Column("nome")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Column("cpf")]
        [Display(Name = "CPF")]
        public string CPF { get; set; }

        [Column("datanascimento")]
        [Display(Name = "Data de Nascimento")]
        public string DataNascimento { get; set; }
    }
}

Web_CRUD_Contatos/Controllers/ContatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using iTextSharp.text.xml;
using iTextSharp.tool.xml.html;
using MessagePack;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Plugins;
using Org.BouncyCastle.Asn1.Cmp;
using Web_CRUD_Contatos.Models;

namespace Web_CRUD_Contatos.Controllers
{
    public class ContatosController : Controller
    {
        private readonly Contexto _context;

        public ContatosController(Contexto context)
        {
            _context = context;
        }

        // GET: Contatos
        public async Task<IActionResult> Index()
        {
              return View(await _context.Contato.ToListAsync());
        }

        // GET: Contatos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contato == null)
            {
                return NotFound();
            }

            var contato = await _context.Contato
                .FirstOrDefaultAsync(m => m.id == id);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);
        }

        // GET: Contatos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contatos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Nome,CPF,DataNascimento")] Contato contato)
        {               

            ValidaCPF validaCPF = new ValidaCPF();

            try
            {
                if (ModelState.IsValid & validaCPF.IsCpf(contato.CPF))
                {
                    _context.Add(contato);
                    await _context.SaveChangesAsync();                   
                
                    TempData["MessagemSucessoAdd"] = "Aluno adicionado com sucesso!!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["MessagemErrorCPF"] = "CPF invalido!!";
                    return RedirectToAction(nameof(Create));
                }

            }
            catch(System.Exception ex)
            {
                TempData["MessagemErrorCPF"] = "CPF invalido!!";
                return RedirectToAction(nameof(Create));

            }
            return View(contato);
        }

 

        // GET: Contatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contato == null)
            {
                return NotFound();
            }

            var contato = await _context.Contato.FindAsync(id);
            if (contato == null)
            {
                return NotFound();
            }
            return View(contato);
        }

        // POST: Contatos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Nome,CPF,DataNascimento")] Contato contato)
        {
            if (id != contato.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContatoExists(contato.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contato);
        }

        // GET: Contatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contato == null)
            {
                return NotFound();
            }

            var contato = await _context.Contato
                .FirstOrDefaultAsync(m => m.id == id);
            if (contato == null)
            {
                return NotFound();
            }

            return View(contato);
        }

        // POST: Contatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contato == null)
            {
                return Problem("Entity set 'Contexto.Contato'  is null.");
            }
            var contato = await _context.Contato.FindAsync(id);
            if (contato != null)
            {
                _context.Contato.Remove(contato);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContatoExists(int id)
        {
          return _context.Contato.Any(e => e.id == id);
        }
    }
}

Web_CRUD_Contatos/Views/Contatos/Create.cshtml
@model Web_CRUD_Contatos.Models.Contato

@{
    ViewData["Adicionar um novo Contato"] = "Create";
}


<h1>Adicionar um novo aluno</h1>
 @if (TempData["MessagemErrorCPF"] != null)
    {
    <div class="alert alert-danger" role="alert">
        <button type= "button" class = "btn btn-danger btn-sm close-alert" arial-label ="Close">x</button>
        @TempData["MessagemErrorCPF"]
    </div>
    }


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" placeholder="Nome Completo"/>
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control"placeholder="CPF ex: 04568083911" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>            
            <br />
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" type="date" class="form-control"/>                
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Adicionar" class="btn btn-primary" onclick="IsCpf(CPF)"/>                
                <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index">Voltar</a>
        </form> 
    </div>
</div>

<div>

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Web_CRUD_Contatos/Views/Contatos/Delete.cshtml
@model Web_CRUD_Contatos.Models.Contato

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar Aluno</h1>

<h3>Você tem certeza que quer apagar esse Aluno?</h3>
<div>    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> 
        <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index">Voltar</a>
        
    </form>
</div>

Web_CRUD_Contatos/Views/Contatos/Details.cshtml
@model Web_CRUD_Contatos.Models.Contato

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contato</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web_CRUD_Contatos/Views/Contatos/Edit.cshtml
@model Web_CRUD_Contatos.Models.Contato

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-controller="Contatos" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

<div>
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web_CRUD_Contatos/Views/Contatos/Index.cshtml
@model IEnumerable<Web_CRUD_Contatos.Models.Contato>

@{
    ViewData["Title"] = "Lista de Alunos";
}
<h1>Lista de Alunos</h1>

@if (TempData["MessagemSucessoAdd"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type= "button" class = "btn btn-danger btn-sm close-alert" arial-label ="Close">x</button>
        @TempData["MessagemSucessoAdd"]
    </div>
}
<p>   
    <a class="btn btn-success" asp-action="Create">Adicionar um novo aluno</a>    
</p>

<table class="table" id = "table-contatos">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>              
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.id">Editar</a>                 
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>