Web_CRUD_Contatos/Models/Matriculas.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;

namespace Web_CRUD_Contatos.Models
{
    
    public class Matriculas
    {       
        public int id { get; set; }

        [Column("Nome")]
        [Display(Name = "Nome do Aluno")]
        public string Nome { get; set; }

        [Column("CPF")]
        [Display(Name = "CPF do Aluno")]
        public string CPF { get; set; }
        
        [Column("NomeCurso")]
        [Display(Name = "Nome do Curso")]
        public string NomeCurso { get; set; }

        
        [NotMapped]
        public List<SelectListItem>? ContatosSelectListNome { get; set; }

        [NotMapped]
        public List<SelectListItem>? ContatosSelectListCPF { get; set; }

        [NotMapped]
        public List<SelectListItem>? ContatosSelectListCurso { get; set; }
    }
    
}

Web_CRUD_Contatos/Controllers/MatriculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_CRUD_Contatos.Models;
using System.Data;
using System.Data.SqlClient;
using Web_CRUD_Contatos.Migrations;

namespace Web_CRUD_Contatos.Controllers
{
    public class MatriculasController : Controller
    {
     
        private readonly Contexto _context;

        public MatriculasController(Contexto context)
        {
            _context = context;
        }

        // GET: Matriculas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Matriculas.ToListAsync());
        }

        // GET: Matriculas/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null || _context.Matriculas == null)
            {
                return NotFound();
            }

            var matriculas = await _context.Matriculas
                .FirstOrDefaultAsync(m => m.id == id);
            if (matriculas == null)
            {
                return NotFound();
            }
            return View(matriculas);
        }

        // GET: Matriculas/Create
        public IActionResult Create()
        {
            Matriculas matriculas = new Matriculas();

             matriculas.ContatosSelectListNome = new List<SelectListItem>();

             matriculas.ContatosSelectListCPF = new List<SelectListItem>();

             matriculas.ContatosSelectListCurso = new List<SelectListItem>();

             foreach (var contatos in _context.Contato)
             {
                matriculas.ContatosSelectListCPF.Add(new SelectListItem { Text = contatos.CPF });

                matriculas.ContatosSelectListNome.Add(new SelectListItem { Text =  contatos.Nome});
                
             }

             foreach (var cursos in _context.Curso)
             {
                 matriculas.ContatosSelectListCurso.Add(new SelectListItem { Text = cursos.Nome });

             }

             return View(matriculas);
            

        }        


        // POST: Matriculas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Nome,CPF,NomeCurso")] Matriculas matriculas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(matriculas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(matriculas);

        }
       

        // GET: Matriculas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Matriculas == null)
            {
                return NotFound();
            }

            var matriculas = await _context.Matriculas.FindAsync(id);
            if (matriculas == null)
            {
                return NotFound();
            }
            return View(matriculas);
        }

        // POST: Matriculas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Nome,CPF,NomeCurso")] Matriculas matriculas)
        {
            if (id != matriculas.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(matriculas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatriculasExists(matriculas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(matriculas);
        }

        // GET: Matriculas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Matriculas == null)
            {
                return NotFound();
            }

            var matriculas = await _context.Matriculas
                .FirstOrDefaultAsync(m => m.id == id);
            if (matriculas == null)
            {
                return NotFound();
            }

            return View(matriculas);
        }

        // POST: Matriculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Matriculas == null)
            {
                return Problem("Entity set 'Contexto.Matriculas'  is null.");
            }
            var matriculas = await _context.Matriculas.FindAsync(id);
            if (matriculas != null)
            {
                _context.Matriculas.Remove(matriculas);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MatriculasExists(int id)
        {
            return _context.Matriculas.Any(e => e.id == id);
        }

       
    }
}

Web_CRUD_Contatos/Views/Matriculas/Create.cshtml
@model Web_CRUD_Contatos.Models.Matriculas


@{
    ViewData["Title"] = "Create";  
}
<h4>Matricular Um Aluno</h4>
<hr />
<div class="row">    
        <form asp-action="Create">           
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <select input asp-for="CPF" class="form-select" asp-items="Model.ContatosSelectListCPF"></select>                   
                <span asp-validation-for="CPF" class="text-danger"></span>
                <br />
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <select input asp-for="Nome" class="form-select" asp-items="Model.ContatosSelectListNome"></select>                
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="NomeCurso" class="control-label"></label>
                <select input asp-for="NomeCurso" class="form-select" asp-items="Model.ContatosSelectListCurso"></select>   
                <span asp-validation-for="NomeCurso" class="text-danger"></span>
            </div>            
            <br />
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-controller="Matriculas" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

Web_CRUD_Contatos/Views/Matriculas/Delete.cshtml
@model Web_CRUD_Contatos.Models.Matriculas

@{
    ViewData["Title"] = "Delete";
   
}


<h3>Tem certeza que deseja apagar essa matricula?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeCurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeCurso)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Apagar" class="btn btn-danger" />
        <a class="btn btn-primary" asp-action="Index">Voltar</a>
    </form>
</div>

Web_CRUD_Contatos/Views/Matriculas/Details.cshtml
@model Web_CRUD_Contatos.Models.Matriculas

@{
    ViewData["Title"] = "Details";
   
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<h1>Details</h1>

<div>
    <h4>Matriculas</h4>
    <hr />
    <dl class="row">        
        <div class="col-sm-4">
            <form>
                <div class="form-group">
                    <label class="control-labber">Nome do Aluno</label>
                    <select id="ddlNomeContato"class="form-control" asp-items="@(new SelectList(ViewBag.NomeList, "Value", "Text"))"></select>
                </div>
                <div class="form-group">
                    <label class="control-labber">CPF do Aluno</label>
                    <select id="ddlCpfContato"class="form-control" asp-items="@(new SelectList(string.Empty, "Value", "Text"))"></select>
                </div>
            </form>
        </div>
        <div class="col-sm-4"></div>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeCurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeCurso)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<script>
    $(function(){
        $("#ddlNomeContato").change(function(){
            $.getJSON("/Matriculas/GetCpf", { cpf: #$("#ddlNomeContato").val()}, function(d){
            var row = "";
            $("#ddlCpfContato").empty();
            $.each(d, function(i, v){
                row += "<option value=" + v.value + ">v.text+</option>";
            });
            $("#ddlCPFContato").html(row);
            })
        })
        $("#ddlCpfContato").change(function(){
            $.getJSON("/Matriculas/GetNome", { cpf: #$("#ddlCpfContato").val()}, function(d){
            var row = "";
            $("#ddlCpfContato").empty();
            $.each(d, function(i, v){
                row += "<option value=" + v.value + ">v.text+</option>";
            });
            $("#ddlCpfContato").html(row);
            })
        })
    })
</script>

Web_CRUD_Contatos/Views/Matriculas/Edit.cshtml
@model Web_CRUD_Contatos.Models.Matriculas

@{
    ViewData["Title"] = "Edit";
    
}

<h1>Editar Matricula</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomeCurso" class="control-label"></label>
                <input asp-for="NomeCurso" class="form-control" />
                <span asp-validation-for="NomeCurso" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>
<br />

Web_CRUD_Contatos/Views/Matriculas/Index.cshtml
@model IEnumerable<Web_CRUD_Contatos.Models.Matriculas>

@{
    ViewData["Title"] = "Realizar uma matricula";
}
<h1>Lista de alunos matriculados</h1>


<h1></h1>

<p>    
    <a class="btn btn-success" asp-action="Create">Matricular um aluno</a>
</p>
<table class="table" id="table-matriculas">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomeCurso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeCurso)
            </td>
            <td>
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.id">Editar</a>                 
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>